handle:
- rewrite: if(!is_dir() && !is_file()) goto "index.php?%{QUERY_STRING}"
- compress:  if ( out_header["Content-type"] ~ "text/css" ) compress
- compress:  if ( out_header["Content-type"] ~ "text/javascript" ) compress
- compress:  if ( out_header["Content-type"] ~ "application/javascript" ) compress
- compress:  if ( out_header["Content-type"] ~ "application/octet-stream" ) compress
- compress:  if ( out_header["Content-type"] ~ "text/html" ) compress
- compress:  if ( out_header["Content-type"] ~ "application/zip" ) compress
- compress:  if ( out_header["Content-type"] ~ "application/x-zip-compressed" ) compress
- compress:  if ( out_header["Content-type"] ~ "application/pdf" ) compress
- compress:  if ( out_header["Content-type"] ~ "text/plain" ) compress
- compress:  if ( out_header["Content-type"] ~ "image/jpeg" ) compress
- compress:  if ( out_header["Content-type"] ~ "image/png" ) compress
- compress:  if ( out_header["Content-type"] ~ "image/gif" ) compress
- compress:  if ( out_header["Content-type"] ~ "application/x-shockwave-flash" ) compress
